<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('members')->insert([
            ['name' => 'AFIF FIRDAUS BIN MOHD ZULKIFLI', 'matric_no' => 'D20231105931', 'batch' => 'Valta'],
            ['name' => 'AFIQAH AQILAH BINTI CHE JAMIL', 'matric_no' => 'D20231106930', 'batch' => 'Valta'],
            ['name' => 'AHMAD MUHAMMAD BIN JASMI', 'matric_no' => 'D20231108364', 'batch' => 'Valta'],
            ['name' => 'AIDA FARHANA BINTI MOHD ARSHAD', 'matric_no' => 'D20231108684', 'batch' => 'Valta'],
            ['name' => 'AIMAN BIN MOHD HISHAM', 'matric_no' => 'D20231106397', 'batch' => 'Valta'],
            ['name' => 'ANWAR ZAKARIA BIN ABD RAHMAN', 'matric_no' => 'D20231108164', 'batch' => 'Valta'],
            ['name' => 'DORITHY SASHA ANAK UBANG', 'matric_no' => 'D20231105604', 'batch' => 'Valta'],
            ['name' => 'EISYA NUR HUMAIRA BINTI MOHD NORAZMI', 'matric_no' => 'D20231107614', 'batch' => 'Valta'],
            ['name' => 'HARITH TAHFIZ BIN ABD AZIZ', 'matric_no' => 'D20231108879', 'batch' => 'Valta'],
            ['name' => 'INSYIRAH ZAHIRAH BINTI MATZIN', 'matric_no' => 'D20231106141', 'batch' => 'Valta'],
            ['name' => 'IRFAN HAKIM BIN ISHAK', 'matric_no' => 'D20231106451', 'batch' => 'Valta'],
            ['name' => 'KHAIRUNNISA BINTI HOSDI', 'matric_no' => 'D20231106503', 'batch' => 'Valta'],
            ['name' => 'LEE HUI YI', 'matric_no' => 'D20231106300', 'batch' => 'Valta'],
            ['name' => 'MIMI AZWA BINTI LEMAN', 'matric_no' => 'D20231108892', 'batch' => 'Valta'],
            ['name' => 'MINSYA NUR DIANA BINTI MUHAMAD BURHANORDIN', 'matric_no' => 'D20231108897', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD ADAM BIN MAZLAN', 'matric_no' => 'D20231108067', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD ADIB HAIKAL BIN ANUAR', 'matric_no' => 'D20231106004', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD ALIFF SYAZRIL BIN JAMALUDIN', 'matric_no' => 'D20231105486', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD AMIRUL HAKIMI BIN HAMDI', 'matric_no' => 'D20231107694', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD ARASH BIN HASZELAN', 'matric_no' => 'D20231107697', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD ARIF BIN ZAHARUDIN', 'matric_no' => 'D20231106538', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD FAHMI IDHAM BIN MUSA', 'matric_no' => 'D20231105850', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD HAFIZ HAIKAL BIN KAMARUDIN', 'matric_no' => 'D20231107910', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD HANEEF BIN SHAHUL HAMEED', 'matric_no' => 'D20231108640', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD HARIZ HUSAINI BIN AZMI', 'matric_no' => 'D20231108465', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD IRMAN BIN IRWAN', 'matric_no' => 'D20231106440', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD QAYYIM HADIF BIN NAZARMASAGOS', 'matric_no' => 'D20231107435', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD SHARUL AIMAN BIN SHAHROM', 'matric_no' => 'D20231108108', 'batch' => 'Valta'],
            ['name' => 'MUHAMMAD SYAFILI BIN A.GHANI', 'matric_no' => 'D20231108077', 'batch' => 'Valta'],
            ['name' => 'NISRINA NABIHAH BINTI ZURIN', 'matric_no' => 'D20231105899', 'batch' => 'Valta'],
            ['name' => 'NOR AZLINA BINTI MOHD ARIFIN', 'matric_no' => 'D20231107771', 'batch' => 'Valta'],
            ['name' => 'NORSABILLA BALQIS BINTI KAMARUL NIZAM', 'matric_no' => 'D20231107712', 'batch' => 'Valta'],
            ['name' => 'NUHA FARISHA BINTI MOHD JAIDI', 'matric_no' => 'D20231105840', 'batch' => 'Valta'],
            ['name' => 'NUR AISHAH BINTI MOHAMMAD', 'matric_no' => 'D20231106560', 'batch' => 'Valta'],
            ['name' => 'NUR ALIA MAISARA BINTI MOHAMAD RIZZAL', 'matric_no' => 'D20231107028', 'batch' => 'Valta'],
            ['name' => 'NUR AMALIN SYAFIQAH BINTI AZIZ', 'matric_no' => 'D20231108172', 'batch' => 'Valta'],
            ['name' => 'NUR AQILAH QAISARA BINTI SHAHRIZAL', 'matric_no' => 'D20231108168', 'batch' => 'Valta'],
            ['name' => 'NUR FARDIYANA BINTI AZMIH', 'matric_no' => 'D20231105663', 'batch' => 'Valta'],
            ['name' => 'NUR FISYARH AYUNI BINTI MUHAMED FAIZAL', 'matric_no' => 'D20231107138', 'batch' => 'Valta'],
            ['name' => 'NUR HASHA HERDINA BINTI HASRUL HISHAM', 'matric_no' => 'D20231107530', 'batch' => 'Valta'],
            ['name' => 'NUR IMANIENA WAHEEDA BINTI ISMAIL', 'matric_no' => 'D20231107274', 'batch' => 'Valta'],
            ['name' => 'NUR NATASHA HANIM BINTI AZMI', 'matric_no' => 'D20231105639', 'batch' => 'Valta'],
            ['name' => 'NUR RAIHANAH BINTI MAIL', 'matric_no' => 'D20231107443', 'batch' => 'Valta'],
            ['name' => 'NUR SHARHAINA BINTI RASIMAN', 'matric_no' => 'D20231107793', 'batch' => 'Valta'],
            ['name' => 'NUR SYAFEQA ZULAIKHA BINTI ZUR’AINI', 'matric_no' => 'D20231108655', 'batch' => 'Valta'],
            ['name' => 'NURFARAH ELYSSA BT MOHD MUSTAPHA', 'matric_no' => 'D20231107329', 'batch' => 'Valta'],
            ['name' => 'NURIN SOFEA BINTI ZAHARI', 'matric_no' => 'D20231108185', 'batch' => 'Valta'],
            ['name' => 'NURSYAFIQAH MADIHAH BINTI ALI', 'matric_no' => 'D20231108673', 'batch' => 'Valta'],
            ['name' => 'NURUL AL NISHAH BINTI ABDUL MUHID', 'matric_no' => 'D20231107775', 'batch' => 'Valta'],
            ['name' => 'NURUL ATHIRAH BINTI SUHAIMI', 'matric_no' => 'D20231107927', 'batch' => 'Valta'],
            ['name' => 'NURUL NADIA BINTI ABDUL MALIK', 'matric_no' => 'D20231107557', 'batch' => 'Valta'],
            ['name' => 'SHAHRUL NIZAM BIN RAMLI', 'matric_no' => 'D20231106149', 'batch' => 'Valta'],
            ['name' => 'SITI AFIQAH BINTI MOHAMAD HANIF', 'matric_no' => 'D20231105852', 'batch' => 'Valta'],
            ['name' => 'SITI AISYAH BINTI AZIZAN', 'matric_no' => 'D20231108910', 'batch' => 'Valta'],
            ['name' => 'SITI NURFATIHAH BINTI AZMAN', 'matric_no' => 'D20231107938', 'batch' => 'Valta'],
            ['name' => 'TAMIL AMUTHAN A/L ARUMUGAM', 'matric_no' => 'D20231106276', 'batch' => 'Valta'],
            ['name' => 'TENGKU HAZIQ NAIM BIN TENGKU MOKHTAR', 'matric_no' => 'D20231106540', 'batch' => 'Valta'],
            ['name' => 'WAN NUR AFIQAH BINTI WAN MOHD ZUNAIDI', 'matric_no' => 'D20231107687', 'batch' => 'Valta'],
            ['name' => 'AHMAD DANISH HAIKAL BIN AHMAD KAMAL', 'matric_no' => 'D20241112137', 'batch' => 'Valor'],
            ['name' => 'AHMAD IZZAT BIN KHALID', 'matric_no' => 'D20241112016', 'batch' => 'Valor'],
            ['name' => 'AHMAD JAAFAR SHODIQ BIN MELI', 'matric_no' => 'D20241110664', 'batch' => 'Valor'],
            ['name' => 'AHMAD SYAMIL BIN AYUB', 'matric_no' => 'D20241111750', 'batch' => 'Valor'],
            ['name' => 'AINI AMALIN BINTI GHAZALI', 'matric_no' => 'D20241111251', 'batch' => 'Valor'],
            ['name' => 'ALIFF AIMAN BIN MOHD HALILI', 'matric_no' => 'D20241113799', 'batch' => 'Valor'],
            ['name' => 'ANIS HANNANI BINTI SAIDI', 'matric_no' => 'D20241110379', 'batch' => 'Valor'],
            ['name' => 'ATIFURRAHMAH BINTI RADZLI', 'matric_no' => 'D20241110823', 'batch' => 'Valor'],
            ['name' => 'AVINITHA A/P SIVALINGGAM', 'matric_no' => 'D20241109580', 'batch' => 'Valor'],
            ['name' => 'AZAMUDDIN BIN AZAHARI', 'matric_no' => 'D20241112370', 'batch' => 'Valor'],
            ['name' => 'CHRISTHOPHER FERNANDEZ ANAK RUDY', 'matric_no' => 'D20241109980', 'batch' => 'Valor'],
            ['name' => 'DHIA SYAHIN BINTI BAHARUDIN', 'matric_no' => 'D20241111812', 'batch' => 'Valor'],
            ['name' => 'HALIMATUL SADIAH BINTI MOHD ALWI', 'matric_no' => 'D20241111260', 'batch' => 'Valor'],
            ['name' => 'HANI NABILAH BINTI AZAHARI', 'matric_no' => 'D20241113388', 'batch' => 'Valor'],
            ['name' => 'HASMIZI BIN SUHAILI', 'matric_no' => 'D20241110122', 'batch' => 'Valor'],
            ['name' => 'IKMAL HANAFI BIN SJIAOLA', 'matric_no' => 'D20241111733', 'batch' => 'Valor'],
            ['name' => 'JASLI BIN JAIPI', 'matric_no' => 'D20241112519', 'batch' => 'Valor'],
            ['name' => 'JULIA QISTINA BINTI MOHD SHUKRI HADAFI', 'matric_no' => 'D20241112879', 'batch' => 'Valor'],
            ['name' => 'KESAHVARTHINI A/P SEGAR', 'matric_no' => 'D20241113586', 'batch' => 'Valor'],
            ['name' => 'LAWIE ANAK JANIN', 'matric_no' => 'D20241113899', 'batch' => 'Valor'],
            ['name' => 'LIA IXORA BINTI JAFRI', 'matric_no' => 'D20241109776', 'batch' => 'Valor'],
            ['name' => 'MASNIRA A/P AWANG', 'matric_no' => 'D20241112147', 'batch' => 'Valor'],
            ['name' => 'MICHELLE ANDREA ANAK PETER', 'matric_no' => 'D20241110415', 'batch' => 'Valor'],
            ['name' => 'MOHAMAD IRSYAD BIN MOHAMAD KUSHAIRI', 'matric_no' => 'D20241111777', 'batch' => 'Valor'],
            ['name' => 'MOHAMAD ROHAIZAT BIN JOHARI', 'matric_no' => 'D20241109659', 'batch' => 'Valor'],
            ['name' => 'MOHAMMAD NUR AIMAN BIN ABDULLAH', 'matric_no' => 'D20241110080', 'batch' => 'Valor'],
            ['name' => 'MOHAMMAD SYAFIE BIN ABDUL LATIP', 'matric_no' => 'D20241110618', 'batch' => 'Valor'],
            ['name' => 'MUHAMAD SHUKRI BIN ROSDY', 'matric_no' => 'D20241111335', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD AIMAN BIN MOHD ASRI', 'matric_no' => 'D20241111922', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD AMIR AMZAR BIN ABD RAHIM', 'matric_no' => 'D20241109606', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD AMMAR BAIHAQI BIN MOHAMAD AZMADI', 'matric_no' => 'D20241111250', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD AQLAN AFIF BIN MOHD SUKRI', 'matric_no' => 'D20241111855', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD EYZAL BIN NAZRI', 'matric_no' => 'D20241113337', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD FIKRI AIMAN BIN AZEMI', 'matric_no' => 'D20241110649', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD FATHUL BAHIR BIN AZMAN', 'matric_no' => 'D20241113791', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD IRFAN SHAUQI BIN IBRAHIM', 'matric_no' => 'D20241111998', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD NAJIB SYUKRI BIN MAKSALMINA', 'matric_no' => 'D20241112006', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD NAUFAL BIN NORAZLEY', 'matric_no' => 'D20241112151', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD NAZMI BIN PUAD', 'matric_no' => 'D20241112399', 'batch' => 'Valor'],
            ['name' => 'MOHAMAD SALAHUDDIN BIN MOHD YUNUS', 'matric_no' => 'D20241112109', 'batch' => 'Valor'],
            ['name' => 'MUHAMMAD SHAHRIN', 'matric_no' => 'D20241113054', 'batch' => 'Valor'],
            ['name' => 'NICKLYIEANNA EZRA MUNING', 'matric_no' => 'D20241113102', 'batch' => 'Valor'],
            ['name' => 'NOR ADLINDA ATIRAH BINTI MOHD FAIZOL', 'matric_no' => 'D20241112380', 'batch' => 'Valor'],
            ['name' => 'NUR ADILAH BINTI MOHD RUSDI', 'matric_no' => 'D20241110730', 'batch' => 'Valor'],
            ['name' => 'NUR AINA IZZATI BINTI HARUN', 'matric_no' => 'D20241110937', 'batch' => 'Valor'],
            ['name' => 'NUR ALWA SAFINA BINTI KHAIRUL AZHA', 'matric_no' => 'D20241112362', 'batch' => 'Valor'],
            ['name' => 'NUR ALYA ARISSA BINTI IBRAHIM', 'matric_no' => 'D20241113220', 'batch' => 'Valor'],
            ['name' => 'NUR AMIRAH SAFIA BINTI ZAKARIA', 'matric_no' => 'D20241109815', 'batch' => 'Valor'],
            ['name' => 'NUR AZURASAFIANI BINTI SHAPIE', 'matric_no' => 'D20241110718', 'batch' => 'Valor'],
            ['name' => 'NUR ELYANA ATIKAH BINTI SIDI AHMAD', 'matric_no' => 'D20241110241', 'batch' => 'Valor'],
            ['name' => 'NUR FAQIRAH HANIS BINTI MOHD FAIZAL', 'matric_no' => 'D20241111525', 'batch' => 'Valor'],
            ['name' => 'NUR LINA KHALIDAH BINTI RAZALI', 'matric_no' => 'D20241111602', 'batch' => 'Valor'],
            ['name' => 'NUR SYAFIQAH BINTI MUSA', 'matric_no' => 'D20241112462', 'batch' => 'Valor'],
            ['name' => 'NURIN QISTINA AMEEN BINTI MAHATHIR', 'matric_no' => 'D20241110587', 'batch' => 'Valor'],
            ['name' => 'NURSYAFIKAH AISYAH BINTI MOHD KASRI', 'matric_no' => 'D20241110456', 'batch' => 'Valor'],
            ['name' => 'NORUL AQILAH BINTI MOHD RAFI E', 'matric_no' => 'D20241112020', 'batch' => 'Valor'],
            ['name' => 'NURUL HUDA BINTI ASHIKIN', 'matric_no' => 'D20241113229', 'batch' => 'Valor'],
            ['name' => 'NURUL NAJIHAH BINTI HAMZI', 'matric_no' => 'D20241111394', 'batch' => 'Valor'],
            ['name' => 'PUTERI NUR ADRIANA BINTI FAIZAL', 'matric_no' => 'D20241111403', 'batch' => 'Valor'],
            ['name' => 'RADIYATUL ADAWIYA BINTI OSMAN', 'matric_no' => 'D20241111618', 'batch' => 'Valor'],
            ['name' => 'RUHI HASSINI BINTI MUHAMAD NUBLI', 'matric_no' => 'D20241112376', 'batch' => 'Valor'],
            ['name' => 'SAMSINAR BINTI ARIFAI', 'matric_no' => 'D20241111087', 'batch' => 'Valor'],
            ['name' => 'SATHISHA A/P MANIMARAN', 'matric_no' => 'D20241113046', 'batch' => 'Valor'],
            ['name' => 'SITI NURBALQIS BINTI AHMAD', 'matric_no' => 'D20241111975', 'batch' => 'Valor'],
            ['name' => 'SLYVESTER NANTA ANAK GRAMAN', 'matric_no' => 'D20241113466', 'batch' => 'Valor'],
            ['name' => 'WAN MUHAMMAD FATHI BINTI WAN ZULKIFLI', 'matric_no' => 'D20241109668', 'batch' => 'Valor'],
            ['name' => 'WAN MUHAMMAD PUTERA SYAH BIN MUSTAFFAR', 'matric_no' => 'D20241110965', 'batch' => 'Valor'],
            ['name' => 'YUSNINA MARIA ANAK MURIE', 'matric_no' => 'D20241113280', 'batch' => 'Valor'],
            ['name' => 'ZAID AL-MATABIDILLAH BIN JEMINGAN', 'matric_no' => 'D20241112525', 'batch' => 'Valor'],
            ['name' => 'ZULKARNAIN BIN FAUZI', 'matric_no' => 'D20241109535','batch' => 'Valor' ],
            ['name' => 'AGUSMAN BIN ABDULLAH', 'matric_no' => 'D20221102791', 'batch' => 'Kesatria Biru'],
            ['name' => 'AHMAD ZULKARNAIN BIN PUZELAN', 'matric_no' => 'D20221101758', 'batch' => 'Kesatria Biru'],
            ['name' => 'AIMAN BIN NOR AKBAR', 'matric_no' => 'D20221102800', 'batch' => 'Kesatria Biru'],
            ['name' => 'AIMAN SYUKRI BIN MOHD AFFANDI', 'matric_no' => 'D20221103723', 'batch' => 'Kesatria Biru'],
            ['name' => 'AINUN ZAHIAH BINTI ROSLI', 'matric_no' => 'D20221103790', 'batch' => 'Kesatria Biru'],
            ['name' => 'ANIS ARISYA BINTI ZAHARI', 'matric_no' => 'D20221101922', 'batch' => 'Kesatria Biru'],
            ['name' => 'AYNA BALQIS BINTI MOHAMAD KHAIRUDDIN', 'matric_no' => 'D20221101947', 'batch' => 'Kesatria Biru'],
            ['name' => 'BADRULHISHAM BIN MOHAMAD', 'matric_no' => 'D20221102221', 'batch' => 'Kesatria Biru'],
            ['name' => 'BALQIS AN NISA’ BINTI MOHD NAWIYAH', 'matric_no' => 'D20221103340', 'batch' => 'Kesatria Biru'],
            ['name' => 'DAHLIA FARISAH BINTI DERIN', 'matric_no' => 'D20221102244', 'batch' => 'Kesatria Biru'],
            ['name' => 'DAYANG NUR JANNAH ELYSHA BINTI JOHAN', 'matric_no' => 'D20221102915', 'batch' => 'Kesatria Biru'],
            ['name' => 'DIMITRUS ANAK SHEAT', 'matric_no' => 'D20221102945', 'batch' => 'Kesatria Biru'],
            ['name' => 'DINI AMIN BIN YUSDI', 'matric_no' => 'D20221102406', 'batch' => 'Kesatria Biru'],
            ['name' => 'EMYLIA BINTI SUNYOTO', 'matric_no' => 'D20221103420', 'batch' => 'Kesatria Biru'],
            ['name' => 'FARAH HAAFIZHAH BINTI AZID', 'matric_no' => 'D20221103000', 'batch' => 'Kesatria Biru'],
            ['name' => 'FATIN NOR SYAFIQAH BINTI ZAIDIL AZMAN', 'matric_no' => 'D20221103397', 'batch' => 'Kesatria Biru'],
            ['name' => 'GURUMURTHI A/L JAYCHANDRAN', 'matric_no' => 'D20221102957', 'batch' => 'Kesatria Biru'],
            ['name' => 'HANA HUMAIRAH BINTI MUSA', 'matric_no' => 'D20221101558', 'batch' => 'Kesatria Biru'],
            ['name' => 'HAWA QADEJA BINTI MOHD NAZLI', 'matric_no' => 'D20221102822', 'batch' => 'Kesatria Biru'],
            ['name' => 'LIS ELISA LULA ANAK WILLIAM KILIE', 'matric_no' => 'D20221102714', 'batch' => 'Kesatria Biru'],
            ['name' => 'LYDIA ANAK ELADDIN', 'matric_no' => 'D20221103662', 'batch' => 'Kesatria Biru'],
            ['name' => 'MASYITAH FARHANA BINTI USOP @ MAT KASSIM', 'matric_no' => 'D20221103160', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMAD AFIQ DANIAL BIN MOHD FIRDAUS CHUA', 'matric_no' => 'D20221103598', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMAD AMIRUL HAIRI BIN YAHAYA', 'matric_no' => 'D20221103980', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMAD SHAFIQ BIN ROSTAM', 'matric_no' => 'D20221102680', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMAD SYUKRI AZWAN BIN SHUKERAN', 'matric_no' => 'D20221101523', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMMAD ADRIAN ADRIE BIN ABU BAKAR', 'matric_no' => 'D20221101537', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMMAD AIMAN BIN JUNAIDIH @ JUNAIDI', 'matric_no' => 'D20221101857', 'batch' => 'Kesatria Biru'],
            ['name' => 'MOHAMMAD RAFIQ BIN MOHD RADZI', 'matric_no' => 'D20221103734', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMAD HAKIMI BIN JIRUN', 'matric_no' => 'D20221102816', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMMAD ADAM FITRI BIN MOHD SAHRULNIZAM', 'matric_no' => 'D20221104554', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMMAD AIDID AZRAI BIN AMIR SHAH', 'matric_no' => 'D20221101749', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMAD ALIF BIN NAZMEE', 'matric_no' => 'D20221102842', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMMAD HAFIZ BIN MOHD JALANI', 'matric_no' => 'D20221103832', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMMAD KAMAL HAZIQ BIN ANUARHAFIZ', 'matric_no' => 'D20221103731', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUHAMMAD SUHAILI BIN SUMIRING', 'matric_no' => 'D20221102276', 'batch' => 'Kesatria Biru'],
            ['name' => 'MUSLIMIN BIN HASLAH', 'matric_no' => 'D20221103721', 'batch' => 'Kesatria Biru'],
            ['name' => 'NOR SYAMIMI SOFEA BINTI IBRAHIM', 'matric_no' => 'D20221103587', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR AIN SYAFIQAH BINTI ZURIMANYADZRI', 'matric_no' => 'D20221102270', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR AMALIA BINTI ROSLI', 'matric_no' => 'D20221103672', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR ANIS ALIA BINTI MOHAMED APANDI', 'matric_no' => 'D20221103026', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR ATIQAH BINTI RAZALI', 'matric_no' => 'D20221103808', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR AUFA BINTI SHAMSURI', 'matric_no' => 'D20221102459', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR FATIHAH BINTI HASAN ADLI', 'matric_no' => 'D20221103841', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR NAJMINA BINTI MOHD ASRI', 'matric_no' => 'D20221103654', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR SHAMIMI BINTI MOHD YEZAM', 'matric_no' => 'D20221104405', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR SHAZWANI BINTI AHMAD JAFFRI', 'matric_no' => 'D20221103101', 'batch' => 'Kesatria Biru'],
            ['name' => 'NUR UMI SYAFIKA BINTI ZOLKEFLI', 'matric_no' => 'D20221103321', 'batch' => 'Kesatria Biru'],
            ['name' => 'NURAQILAH BINTI AZMAN', 'matric_no' => 'D20221101589', 'batch' => 'Kesatria Biru'],
            ['name' => 'NURHAZLYNDA BINTI BUSMIN', 'matric_no' => 'D20221102950', 'batch' => 'Kesatria Biru'],
            ['name' => 'NURUL INSYIRAH BINTI MOHD NOR', 'matric_no' => 'D20221103063', 'batch' => 'Kesatria Biru'],
            ['name' => 'NURUL SYAFIQAH BINTI NIK AMRAN', 'matric_no' => 'D20221103633', 'batch' => 'Kesatria Biru'],
            ['name' => 'SHANE ANAK OLIVER CHRISTY', 'matric_no' => 'D20221102807', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI AISYAH BINTI JASMI', 'matric_no' => 'D20221101600', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI ELAYANA BINTI BENSAHUN', 'matric_no' => 'D20221102225', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI HAFIZAH BINTI MOHD ZULHAIRUDDIN', 'matric_no' => 'D20221101622', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI NUR SAIDATUL FAUZA BINTI MUSTAPA', 'matric_no' => 'D20221101687', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI NURMAISARAH BINTI MOHAMAD NIZAM', 'matric_no' => 'D20221102048', 'batch' => 'Kesatria Biru'],
            ['name' => 'SITI NURNAJIHAH BINTI MOHD NOR', 'matric_no' => 'D20221102187', 'batch' => 'Kesatria Biru'],
            ['name' => 'THEVANAYAGAM A/L K.JIWA', 'matric_no' => 'D20221101685', 'batch' => 'Kesatria Biru'],
            ['name' => 'UMIE AYUNIE BINTI MD ISA', 'matric_no' => 'D20221103553', 'batch' => 'Kesatria Biru'],
        ]);
    }
}
